- name: "check ssh key"
  stat:
    path: "{{docker_basedir}}/id_rsa"
  register: ssh_file
  delegate_to: localhost
  run_once: true

- name: "create .ssh dir"
  file:
    path: "/root/.ssh"
    state: directory
    mode: 0600
  delegate_to: localhost
  run_once: true

- name: "ssh gen key"
  when: ssh_file.stat.exists == False
  shell: 'ssh-keygen -b 2048 -t rsa -q -N "" -f {{docker_basedir}}/id_rsa'
  delegate_to: localhost
  run_once: true

- name: "ssh copy key"
  shell: 'cp -f {{docker_basedir}}/id_rsa {{ansible_ssh_private_key_file}} && chmod 0600 {{ansible_ssh_private_key_file}}'
  delegate_to: localhost
  run_once: true

- name: "ssh copy pub key"
  shell: 'cp -f {{docker_basedir}}/id_rsa.pub {{ansible_ssh_private_key_file}}.pub && chmod 0600 {{ansible_ssh_private_key_file}}.pub'
  delegate_to: localhost
  run_once: true

- name: push ssh pub key
  when: push_ssh_key
  authorized_key:
    user: "root"
    key: "{{ lookup('file', '{{ansible_ssh_private_key_file}}.pub') }}"
