- name: prepare work's dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
  - "{{ work_dir }}"

- name: Send and unzip tgz
  copy:
    dest: "{{work_dir}}/{{item}}"
    src: "{{pkg_dir}}/{{item}}"
  with_items:
  - "openvpn-monitor.tgz"

- name: send start template j2
  template:
    dest: "{{work_dir}}/init.sh"
    src: "{{conf_dir}}/init.sh.j2"

- name: "start"
  shell: "bash {{work_dir}}/init.sh"
