- name: prepare work's dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    group: 999
    owner: 999
  with_items:
  - "{{ work_dir }}"
  - "{{ work_dir +'/ldap' }}"
  - "{{ work_dir +'/slapd.d' }}"
  when: install_type == "install"

- name: Send and unzip tgz
  copy:
    dest: "{{work_dir}}/{{item}}"
    src: "{{pkg_dir}}/{{item}}"
  with_items:
  - "openldap.tgz"
  - "phpldapadmin.tgz"
  when: install_type == "install"

- name: send start template j2
  template:
    dest: "{{work_dir}}/init.sh"
    src: "{{conf_dir}}/init.sh.j2"
  when: install_type == "install"

- name: "start"
  shell: "bash {{work_dir}}/init.sh"
  when: install_type == "install"

- name: "del container"
  shell: "docker rm -f {{service_name}} && docker rm -f {{service_name}}admin"
  when: install_type == "delete"

- name: clean all data
  shell: "rm -rf {{ work_dir }}"
  ignore_errors: true
  when: install_type == "delete"