- name: prepare work's dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    group: 999
    owner: 999
  with_items:
  - "{{ work_dir }}"
  - "{{ work_dir +'/ldap' }}"
  - "{{ work_dir +'/slapd.d' }}"

- name: Send and unzip tgz
  copy:
    dest: "{{work_dir}}/{{item}}"
    src: "{{pkg_dir}}/{{item}}"
  with_items:
  - "openldap.tgz"
  - "phpldapadmin.tgz"

- name: send start template j2
  template:
    dest: "{{work_dir}}/init.sh"
    src: "{{conf_dir}}/init.sh.j2"

- name: "start"
  shell: "bash {{work_dir}}/init.sh"
