<<<<<<< HEAD
- name: prepare work's dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    group: 82
    owner: 80
  with_items:
  - "{{ work_dir }}"
  - "{{ work_dir +'/data' }}"
  - "{{ work_dir +'/logs' }}"
  when: install_type == "install"

- name: Send image tgz
  copy:
    dest: "{{work_dir}}/{{item}}"
    src: "{{pkg_dir}}/{{item}}"
  with_items:
  - "changepass.tgz"
  when: install_type == "install"

- name: send start template j2
  template:
    dest: "{{work_dir}}/init.sh"
    src: "{{conf_dir}}/init.sh.j2"
  when: install_type == "install"

- name: "start"
  shell: "bash {{work_dir}}/init.sh"
  when: install_type == "install"

- name: "del container"
  shell: "docker rm -f changepass"
  when: install_type == "delete"

- name: clean all data
  shell: "rm -rf {{ work_dir }}"
  ignore_errors: true
  when: install_type == "delete"
=======
- name: change user passwd custom
  user: name={{ item.user }} password={{ item.password | password_hash('sha512') }}  update_password=always
  with_items:
  - { user: '{{changepass_user}}', password: '{{changepass_password}}' }
>>>>>>> 16b41c129fffd84faba06b2ce714072090c9ae94
