- name: Set sysctl file limits
  pam_limits:
      dest: "{{ item.dest }}"
      domain: '*'
      limit_type: "{{ item.limit_type }}"
      limit_item: "{{ item.limit_item }}"
      value: "{{ item.value }}"
  with_items:
      - { dest: '/etc/security/limits.d/10-nproc.conf',limit_type: 'soft',limit_item: 'nproc', value: '655360' }
      - { dest: '/etc/security/limits.d/10-nproc.conf',limit_type: 'hard',limit_item: 'nproc', value: '655360' }
      - { dest: '/etc/security/limits.d/10-nproc.conf',limit_type: 'soft',limit_item: 'nofile', value: '655360' }
      - { dest: '/etc/security/limits.d/10-nproc.conf',limit_type: 'hard',limit_item: 'nofile', value: '655360' }
  tags:
      - setlimits
