- name: journald ForwardToSyslog set
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: "^#SystemMaxUse="
    line: "SystemMaxUse=2048M"
  become: yes

- name: rsyslogd ForwardToSyslog set
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: "^#ForwardToSyslog=yes"
    line: "ForwardToSyslog=no"
  become: yes

- name: restart journald
  service:
    name: systemd-journald
    state: restarted
  become: yes

- name: copy rsyslog.service
  template:
    src: rsyslog.service.j2
    dest: "/usr/lib/systemd/system/rsyslog.service"

- name: restart rsyslogd
  service:
    name: rsyslog
    state: restarted
  become: yes
